"""add created_at to post

Revision ID: 89996f831534
Revises: 84dc693b4585
Create Date: 2026-05-20 14:03:24.168680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89996f831534'
down_revision: Union[str, Sequence[str], None] = '84dc693b4585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('(CURRENT_TIMESTAMP)')))
    op.drop_column('post', 'date_posted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('date_posted', sa.VARCHAR(), nullable=False))
    op.drop_column('post', 'created_at')
    # ### end Alembic commands ###
